potral/main/urls.py
from django.urls import path
from main.views import *
from . import views

app_name = 'portal'

urlpatterns = [
    path('', views.HomePageView.as_view(), name = 'home'),
    path('news/', views.NewsList.as_view(), name = 'news'),
    path('authors/', views.AuthorsList.as_view(), name = 'authors'),
    path('update/<int:pk>', views.AuthorsUpdateView.as_view(), name='update')
]

potral/potral/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

potral/main/models.py
from django.db import models
from django.test import TestCase

class News(models.Model):
	title = models.CharField("Naslov", max_length=25)
	content = models.TextField("Tekst članka", blank = True, null = True)
	publication_date = models.DateField("Datum objave", blank = True, null = True)

	#Vanjski kljucevi
	author = models.ForeignKey("Author", verbose_name="Author", on_delete=models.CASCADE, blank = True, null = True)
	category_name = models.ForeignKey("Category", verbose_name="Category", on_delete=models.CASCADE, blank = True, null = True)

	def __str__(self):
		return self.title
	



class Author(models.Model):

	name = models.CharField("Ime", max_length=64)
	surname = models.CharField("Prezime", max_length=64)
	email = models.EmailField("Email", blank=True, null=True)
	phone_number = models.CharField("Broj telefona", max_length = 10, blank = True, null = True)

	def __str__(self):
		return self.surname + " " +self.name



class Category(models.Model):
	category_name = models.CharField("Naziv kategorije", max_length=128)

	def __str__(self):
		return self.category_name

potral/main/forms.py
from django import forms
from main.models import Author

class AuthorForm(forms.ModelForm):
    class Meta:
        model=Author
        fields=['name','surname','email','phone_number']

potral/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView, TemplateView
from main.models import News, Author, Category
from django.views import View

from django.urls import reverse_lazy

from main.forms import AuthorForm
from django.views.generic.edit import UpdateView



# Create your views here.

def news(request):
    return render(request, "main/news_list.html")



class HomePageView(View):
    def get(self, request):
        return render(request, 'index.html') 


class NewsList(ListView):
    model = News
    template_name = 'news_list.html'

class AuthorsList(ListView):
    model = Author
    template_name = 'authors_list.html'
    #context_object_name = "portal"

class AuthorsUpdateView(UpdateView):
    model = Author
    from_class = AuthorForm
    template_name = 'update_author.html'
    success_url = reverse_lazy('portal:list')

potral/main/templates/main/authors_list.html
{%extends "index.html"%}
{% block content %}
<h2><strong>Novinari</strong></h2>
<ol class="tekst">
    {% for author in author_list %}
        <p class="autor"> {{ author.name}} {{author.surname}} </p>
        <p class="autor">Kontakt: {{author.phone_number}} </p>
        <p class="autor"> {{ author.email }}</p>
        
        <hr>
    {% endfor %}
</ol>
{% endblock %}

<a href="{% url 'portal:update' portal.pk %}">Upddate</a>

potral/main/templates/main/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

<title>UNIRI portal</title><br><br><br><br><br>

<link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body style = "background-color: #112236;">
    <div style="padding-top:20px;margin-top:0px;">
    <h1>Uniri portal</h1>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="{% url 'portal:home' %}"><img src="{% static 'image.jpg' %} "></a></li>
            <li><a href="{% url 'portal:home' %}"><p class="navbar">Naslovna</p></p></a></li>
            <li><a href="{% url 'portal:news' %}"><p class="navbar">Vijesti</p></a></li>
            <li><a href="{% url 'portal:authors' %}"><p class="navbar">Novinari</p></a></li>
            <li style="float:right; border-left: 1px solid white"><a  href="/admin"> <p class="navbar">Prijava</p> </a></li>    
        </ul>
        {% endblock %}
    </div>

    <div class="content">
        {% block content %}
        <p class="uvod">Dobrodošli na novinski portal Sveučilišta u Rijeci, UNIRI portal.
    </br>Ovdje možete naići na radnom članke godine, te pristupiti podatcima autora istih.</p><br><br>
    <p style="text-align:center;"><img src="{% static 'fidit.jpg' %} " width="50%" height="auto" align="center"></p><br><br><br><br>
    
    {% endblock %}
    </div>
</div>

<div class="footer">
    Izrada: Antonio Kovačev
    </div>
</body>
</html>

potral/main/templates/main/news_list.html
{%extends "index.html"%}

{% block content %}
    <h2><strong>Vijesti</strong></h2><br><br><br><br>
    <ol class="tekst">
        {% for a in news_list %}
            <h3>       {{ a.title }}</h3>
            <p>        {{a.content}}</p><br>
            <h4><p class="autor">Članak napisao: {{ a.author }}</p>
            <p>Kategorija članka: {{a.category_name}}</p>
            <p>Datum objave: {{a.publication_date}}</p><br><br></h4>
            <hr><br><br><br>
        {% endfor %}
    </ol>
{% endblock %}

potral/main/templates/main/update_author.html
<!DOCTYPE html>
<html>
<head>
    <title>Uredi novinara</title>
</head>
<body>
    <h1>Uredi novinara</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Uredi novinara</button>
    </form>
</body>
</html>